[package]
name = "steamium_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
env_logger = "0.11.8"
libsteamium = { path = "../" }
log = "0.4.27"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"
